In [406]:
library(tidyverse)

In [407]:
library(readxl)
library(janitor)
library(stringr)

veg_surveys <- read_excel("datas_and_notebooks/2024/veg_surveys_digitalising.xlsx") |> 
  clean_names() |> 
  mutate(across(where(is.character), ~ str_trim(tolower(.))))

veg_surveys

    date   site plot subplot   diversity id              survival height leaves
1   06.10. a    ao22 ao22-i    1         646             na       26     12
2   nv     a    ao22 ao22-ii   1         316             na       51     7
3   nv     a    ao22 ao22-ii   1         623             NA       54     45
4   nv     a    ao22 ao22-ii   1         1607            na       54     13
5   nv     a    ao22 ao22-iii  1         696             na       62     113
6   nv     a    ao22 ao22-iii  1         647             na       68     6
7   nv     a    ao27 ao27-ii   1         452             na       28     5
8   nv     a    ao27 ao27-ii   1         133x            d        na     na
9   nv     a    ao27 ao27-ii   1         397             na       na     na
10  nv     a    ao27 ao27-ii   1         373             na       na     na
11  nv     a    ao27 ao27-iii  1         440             na       na     na
12  nv     a    ao27 ao27-iii  1         102             a        45     63
13  nv     a    ao27 ao27-iii  1         281             a        NA     na
14  nv     a    ao27 ao27-iii  1         902             na       46     46
15  nv     a    ao27 ao27-iii  1         887             na       64     150
16  nv     a    ao27 ao27-iii  1         133             na       na     na
17  nv     a    ao27 ao27-iv   1         882             na       na     na
18  nv     a    ao27 ao27-iv   1         754             na       na     na
19  nv     a    ap19 ap19-i    4         354             NA       40     49
20  nv     a    ap19 ap19-i    4         401             na       31     77
21  nv     a    ap19 ap19-i    4         989             seedling 8      2
22  nv     a    ap19 ap19-ii   4         304             na       52     91
23  nv     a    ap19 ap19-ii   4         222             na       21     41
24  nv     a    ap19 ap19-ii   4         774             na       75     220
25  nv     a    ap19 ap19-ii   4         903             na       73     160
26  nv     a    ap19 ap19-iii  4         633             na       41     95
27  nv     a    ap19 ap19-iii  4         320             na       na     na
28  nv     a    ap19 ap19-iii  4         471             na       46     86
29  nv     a    ap19 ap19-iii  4         567             na       19     3
30  nv     a    ap19 ap19-iii  4         945             na       27     17
⋮   ⋮      ⋮    ⋮    ⋮         ⋮         ⋮               ⋮        ⋮      ⋮
556 nv     b    bx21 bx21-iv    1        1167            na       na     na
557 nv     b    bi25 bi25-i    NA        1279            na       12.5   3
558 nv     a    ao22 ao22-iii   1        new seedling    NA       9      3
559 nv     a    ao27 ao27-iv    1        281             na       54     42
560 nv     a    ap19 ap19-iii   4        seedling        na       19     3
561 ç      b    bx21 bx21-ii    1        unknown sapling NA       80     61
562 nv     b    bx21 bx21-ii.0  1        nn              na       47     54
563 nv     b    bx21 bx21-iv    1        sapling         NA       65     78
564 nv     b    bx21 bx21-iv    1        sapling         na       30     28
565 nv     b    bx21 bx21-iv    1        sapling         na       46     14
566 nv     b    bx21 bx21-iv    1        sapling         na       37     49
567 nv     b    bx21 bx21-iv    1        sapling         na       39     13
568 nv     b    bx21 bx21-iv    1        sapling         na       103    100
569 nv     b    bx21 bx21-iii   1        sapling         NA       42     27
570 nv     b    bv24 bv24-ii    1        sapling         na       86     122
571 nv     b    bv24 bv24-ii    1        sapling         na       93     73
572 nv     b    bv24 bv24-ii    1        sapling         na       92.5   83
573 nv     b    bv24 bv24-iii   1        unknown sapling na       63.5   22
574 nv     b    bv24 bv24-iii   1        unknown sapling na       43     37
575 nv     b    bv24 bv24-iii   1        unknown sapling na       39     49
576 nv     b    bg28 bg28-iii   2        1315            na       55     34
577 nv     b    bg28 bg28-iii   2        1375            na       54     299
578 nv     b    bg28 bg28-iv    2        NA              na       na     na
579 nv     b    bg28 bg28-i     2        unknown         NA       46     13
580 nv     b    bg28 bg28-i     2        woody           NA       14     5
581 nv     b    bg28 bg28-i     2        unknown         NA       30     7
582 nv     b    bg28 bg28-i     2        sapling         NA       57     17
583 nv     b    bg28 bg28-i     2        sapling         NA       16     5
584 nv     b    bg28 bg28-i     2        sapling         NA       31     32
585 nv     b    bg28 bg28-i     2        sapling         NA       33     17
    number_herbivory_damaged hprop number_fungal_pathogen_damaged fprop
1   12                       2;40  na                             na
2   2                        2;5   na                             na
3   1                        5;99  na                             na
4   13                       10;60 na                             na
5   47                       2;49  na                             na
6   6                        10;40 na                             na
7   5                        5;90  2                              50;50
8   na                       na    na                             na
9   na                       na    na                             na
10  na                       na    na                             na
11  na                       na    na                             na
12  24                       5;80  11                             5;50
13  na                       na    na                             na
14  6                        2;10  7                              2;5
15  12                       1;50  10                             5;50
16  na                       na    na                             na
17  na                       na    na                             na
18  na                       na    na                             na
19  22                       1;40  NA                             na
20  14                       5;40  na                             na
21  0                        0     1                              2
22  72                       5;20  30                             2;40
23  10                       2;20  3                              10;60
24  1;20                     2;5   na                             na
25  5;20                     2;5   na                             na
26  11;23                    10;15 na                             na
27  na                       na    na                             na
28  42                       5;45  na                             na
29  3                        1;70  na                             na
30  2                        5;15  na                             na
⋮   ⋮                        ⋮     ⋮                              ⋮
556 na                       na    na                             na
557 na                       na    na                             na
558 0                        0     na                             na
559 3                        2;60  13                             5;20
560 1                        40    1                              100
561 25                       5;40  1(f)                           5
562 12                       1;25  5                              5;20
563 29                       1;50  /39                            1;50
564 25                       5;80  10                             1;5
565 8                        1;25  6                              5;15
566 43                       5;85  17                             1;15
567 3                        2;20  na                             na
568 29                       5;40  na                             na
569 20                       5;60  na                             na
570 36                       2;40  na                             na
571 34                       5;60  na                             na
572 32                       2;55  na                             na
573 7                        5;55  3n                             10;19
574 2                        10;15 na                             na
575 29                       10;90 na                             na
576 5                        1;20  13;f                           1;20
577 82                       1;80  11;f                           1;20
578 na                       na    na                             na
579 NA                       NA    NA                             NA
580 NA                       NA    NA                             NA
581 3                        1;15  NA                             NA
582 4                        2;5   NA                             NA
583 NA                       40    NA                             NA
584 NA                       2;20  19(f)                          10;30
585 NA                       5;50  9(f                            1;30
    number_necrosis nec_prop notes
1   na              na       NA
2   na              na       cf unlabled
3   na              na       NA
4   na              na       cf unlabled
5   na              na       4b
6   na              na       3b; dying
7   na              na       NA
8   na              na       4b
9   na              na       NA
10  na              na       NA
11  na              na       NA
12  na              na       NA
13  na              na       NA
14  na              na       NA
15  na              na       3b
16  na              na       NA
17  na              na       NA
18  na              na       NA
19  na              na       NA
20  na              na       NA
21  na              na       NA
22  na              na       NA
23  na              na       NA
24  na              na       4b
25  na              na       3b
26  na              na       label corrected in census; 5b
27  na              na       NA
28  na              na       NA
29  na              na       NA
30  na              na       NA
⋮   ⋮               ⋮        ⋮
556 na              na       NA
557 na              na       NA
558 na              na       NA
559 na              na       NA
560 na              na       NA
561 na              na       NA
562 na              na       6b
563 na              na       NA
564 na              na       NA
565 na              na       NA
566 na              na       NA
567 na              na       NA
568 na              na       NA
569 na              na       NA
570 na              na       NA
571 na              na       NA
572 na              na       NA
573 na              na       NA
574 na              na       24 leaves ip
575 na              na       possibly 880
576 na              na       NA
577 na              na       7b
578 na              na       NA
579 NA              NA       NA
580 NA              NA       NA
581 NA              NA       NA
582 NA              NA       NA
583 NA              NA       NA
584 NA              NA       NA
585 NA              NA       NA

In [409]:
veg_surveys <- veg_surveys |> 
  mutate(across(where(is.character), ~ na_if(., "na"))) |> 
  mutate(
    id = if_else(id == "1205sapling", "1205", id),
    leaves = if_else(leaves == "2;3", "230", leaves),
    number_necrosis = if_else(str_detect(number_fungal_pathogen_damaged, "n"), 
                             number_fungal_pathogen_damaged, 
                             number_necrosis),
    nec_prop = if_else(str_detect(fprop, "n"), 
                      paste0(coalesce(nec_prop, ""), fprop), 
                      nec_prop),
    survival = case_when(
      survival == "seedling" ~ "s",
      survival == "woody recruit" ~ "r",
      survival %in% c("*", "27", "15") ~ NA_character_,
      TRUE ~ survival
    ),
    height = str_replace_all(height, ";", ".")
  ) |> 
  separate(number_herbivory_damaged, into = c("number_herbivory_min", "number_herbivory_max"), sep = ";", remove = FALSE) |>
  mutate(
    number_fungal_pathogen_damaged = if_else(str_detect(number_fungal_pathogen_damaged, "n"), NA_character_, number_fungal_pathogen_damaged),
    number_fungal_pathogen_damaged = str_replace_all(number_fungal_pathogen_damaged, ";f|\\(f\\)|\\(f|\\)|\\(|/\\(|f", ""),
    number_fungal_pathogen_damaged = case_when(
      str_detect(number_necrosis, "3f") ~ paste0(coalesce(number_fungal_pathogen_damaged, ""), "3"),
      str_detect(number_necrosis, "0f") ~ paste0(coalesce(number_fungal_pathogen_damaged, ""), "0"),
      TRUE ~ number_fungal_pathogen_damaged
    ),
    number_fungal_pathogen_damaged = case_when(
      number_fungal_pathogen_damaged == "/39" ~ "39",
      number_fungal_pathogen_damaged == "5;19" ~ "19",
      number_fungal_pathogen_damaged == "5;40" ~ "40",
      TRUE ~ number_fungal_pathogen_damaged
    )
  ) |>
  separate(hprop, into = c("hmin", "hmax"), sep = ";", remove = FALSE) |>
  mutate(
    hmin = if_else(hmin == "4(f)", "", hmin)
  )

Warning message:
“Expected 2 pieces. Missing pieces filled with `NA` in 219 rows [1, 2, 3, 4, 5,
6, 7, 12, 14, 15, 19, 20, 21, 22, 23, 28, 29, 30, 31, 33, ...].”
Warning message:
“Expected 2 pieces. Missing pieces filled with `NA` in 15 rows [21, 55, 59, 163,
189, 198, 274, 289, 299, 309, 520, 541, 558, 560, 583].”

In [410]:
veg_surveys <- veg_surveys |>
  dplyr::mutate(
    fprop = dplyr::case_when(
      nec_prop == "10;8(n)" ~ "10",
      nec_prop == "10f/20n" ~ "10",
      nec_prop == "5;10n" ~ "5",
      nec_prop == "40;90n" ~ "40",
      nec_prop == "10;40n" ~ "10",
      nec_prop == "5;15f/40n" ~ "5;15",
      nec_prop == "15;35f/20;30n" ~ "15;35",
      grepl("^5n$", nec_prop) ~ NA_character_,
      TRUE ~ fprop
    ),
    nec_prop = dplyr::case_when(
      nec_prop == "10;8(n)" ~ "8",
      nec_prop == "10f/20n" ~ "20",
      nec_prop == "5;10n" ~ "10",
      nec_prop == "40;90n" ~ "90",
      nec_prop == "10;40n" ~ "40",
      nec_prop == "5;15f/40n" ~ "40",
      nec_prop == "15;35f/20;30n" ~ "20",
      grepl("^5n$", nec_prop) ~ "5",
      grepl("^\\d+%n$", nec_prop) ~ sub("%n$", "", nec_prop),
      TRUE ~ nec_prop
    ),
    # Additional cleaning for fprop
    fprop = dplyr::case_when(
      fprop %in% c("25%n", "10%n") ~ NA_character_,
      grepl("/\\(5-7\\)", fprop) ~ "5;17",
      TRUE ~ fprop
    ),
    # Split fprop into fmin and fmax
    fmin = dplyr::case_when(
      !is.na(fprop) & grepl(";", fprop) ~ sub(";.*", "", fprop),
      !is.na(fprop) ~ fprop,
      TRUE ~ NA_character_
    ),
    fmax = dplyr::case_when(
      !is.na(fprop) & grepl(";", fprop) ~ sub(".*;", "", fprop),
      !is.na(fprop) & !grepl(";", fprop) ~ fprop,
      TRUE ~ NA_character_
    ),
    # Set number_fungal_pathogen_damaged to 15 if it is "10;28"
    number_fungal_pathogen_damaged = dplyr::case_when(
      number_fungal_pathogen_damaged == "10;28" ~ "15",
      TRUE ~ number_fungal_pathogen_damaged
    ),
    # Clean number_necrosis and number_fungal_pathogen_damaged based on rules
    number_necrosis = dplyr::case_when(
      number_necrosis %in% c("4(n)", "4n", "4") ~ "4",
      number_necrosis %in% c("25;n", "25n", "25") ~ "25",
      number_necrosis %in% c("12n", "12") ~ "12",
      number_necrosis %in% c("0f/5n", "Of/5n") ~ "5",
      number_necrosis %in% c("0f/4n", "Of/4n") ~ "4",
      number_necrosis %in% c("1n", "1") ~ "1",
      number_necrosis %in% c("17n", "17") ~ "17",
      number_necrosis %in% c("3f/1n") ~ "1",
      number_necrosis %in% c("3f/2n") ~ "2",
      number_necrosis %in% c("16/1n") ~ "1",
      number_necrosis %in% c("6(n)", "6n", "6") ~ "6",
      number_necrosis %in% c("2n", "2") ~ "2",
      number_necrosis %in% c("n1", "1n") ~ "1",
      number_necrosis %in% c("127n", "127") ~ "127",
      number_necrosis %in% c("3n", "3") ~ "3", number_necrosis %in% c("5n", 5) ~ "5", 
      TRUE ~ number_necrosis
    ),
    number_fungal_pathogen_damaged = dplyr::case_when(
      number_necrosis %in% c("0f/5n", "Of/5n") ~ "0",
      number_necrosis %in% c("0f/4n", "Of/4n") ~ "0",
      number_necrosis == "3f/1n" ~ "3",
      number_necrosis == "3f/2n" ~ "3",
      number_necrosis == "16/1n" ~ "16",
      TRUE ~ number_fungal_pathogen_damaged
    )
  ) |> 
 select(-c(number_herbivory_damaged, hprop, fprop, notes, date))

In [411]:
veg_surveys |> 
 str()

tibble [585 × 17] (S3: tbl_df/tbl/data.frame)
 $ site                          : chr [1:585] "a" "a" "a" "a" ...
 $ plot                          : chr [1:585] "ao22" "ao22" "ao22" "ao22" ...
 $ subplot                       : chr [1:585] "ao22-i" "ao22-ii" "ao22-ii" "ao22-ii" ...
 $ diversity                     : num [1:585] 1 1 1 1 1 1 1 1 1 1 ...
 $ id                            : chr [1:585] "646" "316" "623" "1607" ...
 $ survival                      : chr [1:585] NA NA NA NA ...
 $ height                        : chr [1:585] "26" "51" "54" "54" ...
 $ leaves                        : chr [1:585] "12" "7" "45" "13" ...
 $ number_herbivory_min          : chr [1:585] "12" "2" "1" "13" ...
 $ number_herbivory_max          : chr [1:585] NA NA NA NA ...
 $ hmin                          : chr [1:585] "2" "2" "5" "10" ...
 $ hmax                          : chr [1:585] "40" "5" "99" "60" ...
 $ number_fungal_pathogen_damaged: chr [1:585] NA NA NA NA ...
 $ number_necrosis               : chr [1:585] NA NA NA NA ...
 $ nec_prop                      : chr [1:585] NA NA NA NA ...
 $ fmin                          : chr [1:585] NA NA NA NA ...
 $ fmax                          : chr [1:585] NA NA NA NA ...

In [412]:
sapling_survey_2024 <- read_excel("datas_and_notebooks/2024/Sapling survey 2024.xlsx") |> 
  janitor::clean_names() |> 
  mutate(across(everything(), ~ tolower(str_trim(.)))) |> 
  mutate(across(everything(), ~ ifelse(. == "na", NA, .)))
sapling_survey_2024 |> 
  str()

Warning message:
“Coercing text to numeric in E1237 / R1237C5: '909'”
Warning message:
“Coercing text to numeric in E1238 / R1238C5: '898'”
Warning message:
“Coercing text to numeric in E1241 / R1241C5: '744'”
Warning message:
“Coercing text to numeric in E1242 / R1242C5: '1522'”
Warning message:
“Coercing text to numeric in E1244 / R1244C5: '865'”
Warning message:
“Coercing text to numeric in E1245 / R1245C5: '226'”
New names:
• `` -> `...8`

tibble [1,496 × 24] (S3: tbl_df/tbl/data.frame)
 $ date                          : chr [1:1496] "45438" "45438" "45438" "45438" ...
 $ site                          : chr [1:1496] "a" "a" "a" "a" ...
 $ plot                          : chr [1:1496] "ac32" "ac32" "ac32" "ac32" ...
 $ subplot                       : chr [1:1496] "ac32-i" "ac32-i" "ac32-i" "ac32-i" ...
 $ diversity                     : chr [1:1496] "2" "2" "2" NA ...
 $ id                            : chr [1:1496] "276" "327" "597" "1658" ...
 $ species                       : chr [1:1496] "lindera reflexa" "lindera reflexa" "lindera reflexa" "seedling" ...
 $ x8                            : chr [1:1496] "v" "v" "v" "v" ...
 $ survival                      : chr [1:1496] "a" "1" "1" "s" ...
 $ height                        : chr [1:1496] NA "70" "86" "6" ...
 $ leaves                        : chr [1:1496] NA "93" "250" "6" ...
 $ number_herbivory_damaged      : chr [1:1496] NA "14" "0" "3" ...
 $ hprop                         : chr [1:1496] NA "0.15053763440860216" "0" "0.5" ...
 $ percent_hmin                  : chr [1:1496] NA "0.01" NA "0.2" ...
 $ percent_hmax                  : chr [1:1496] NA "0.5" NA "0.3" ...
 $ number_fungal_pathogen_damaged: chr [1:1496] NA "9" "3" "0" ...
 $ fprop                         : chr [1:1496] NA "9.6774193548387094e-2" "1.2e-2" "0" ...
 $ percent_fmin                  : chr [1:1496] NA "0.01" "0.05" NA ...
 $ percent_fmax                  : chr [1:1496] NA "0.45" "0.15" NA ...
 $ number_necrosis               : chr [1:1496] NA "0" "0" "0" ...
 $ nec_prop                      : chr [1:1496] NA "0" "0" "0" ...
 $ percent_nmin                  : chr [1:1496] NA NA NA NA ...
 $ percent_nmax                  : chr [1:1496] NA NA NA NA ...
 $ notes                         : chr [1:1496] NA NA NA NA ...

In [413]:
(surveys_24 <- sapling_survey_2024 |> 
 #distinct(id) |> 
 full_join(veg_surveys |> 
		   mutate(diversity = as.character(diversity))) |> 
  select(id, everything()))

Joining with `by = join_by(site, plot, subplot, diversity, id, survival,
height, leaves, number_fungal_pathogen_damaged, number_necrosis, nec_prop)`

     id              date  site plot subplot   diversity species
1    276             45438 a    ac32 ac32-i    2         lindera reflexa
2    327             45438 a    ac32 ac32-i    2         lindera reflexa
3    597             45438 a    ac32 ac32-i    2         lindera reflexa
4    1658            45438 a    ac32 ac32-i    NA        seedling
5    1520            45438 a    ac32 ac32-i    NA        quercus sp,
6    1526            45438 a    ac32 ac32-i    NA        seedling
7    666             45438 a    ac32 ac32-ii   2         quercus fabri
8    333             45438 a    ac32 ac32-ii   2         syzygium buxifolium
9    660             45438 a    ac32 ac32-iii  2         adinandra millettii
10   667             45438 a    ac32 ac32-iii  2         buddleja lindleyana
11   716             45438 a    ac32 ac32-iv   2         camellia sinensis
12   349             45438 a    ac32 ac32-iv   2         ilex suaveolens
13   1740            45438 a    ac32 ac32-iv   2         ilex suaveolens
14   1420            45438 a    ac32 ac32-iv   2         seedling
15   1592            45438 a    ac32 ac32-iv   NA        recruit
16   92              45432 a    ae31 ae31-i    1         quercus serrata
17   340             45432 a    ae31 ae31-i    1         quercus serrata
18   250             45432 a    ae31 ae31-ii   1         dalbergia hupeana
19   290             45432 a    ae31 ae31-iii  1         quercus seedling
20   408             45432 a    ae31 ae31-iii  1         ilex pubescens
21   493             45432 a    ae31 ae31-iii  1         ilex pubescens
22   248             45432 a    ae31 ae31-iii  1         rhododendron simsii
23   364             45432 a    ae31 ae31-iii  1         rhododendron simsii
24   211b            45432 a    ae31 ae31-iii  1         rhododendron simsii
25   1697            45432 a    ae31 ae31-iii  1         seedling
26   421             45432 a    ae31 ae31-iv   1         camellia japonica
27   308             45432 a    ae31 ae31-iv   1         loropetalum chinense
28   1951            45432 a    ae31 ae31-iv   1         loropetalum chinense
29   308x            45432 a    ae31 ae31-iv   1         loropetalum chinense
30   302             45432 a    ae31 ae31-iv   1         rhododendron simsii
⋮    ⋮               ⋮     ⋮    ⋮    ⋮         ⋮         ⋮
1910 1203            NA    b    bx21 bx21-iv   1         NA
1911 1279            NA    b    bi25 bi25-i    NA        NA
1912 new seedling    NA    a    ao22 ao22-iii  1         NA
1913 281             NA    a    ao27 ao27-iv   1         NA
1914 seedling        NA    a    ap19 ap19-iii  4         NA
1915 unknown sapling NA    b    bx21 bx21-ii   1         NA
1916 nn              NA    b    bx21 bx21-ii.0 1         NA
1917 sapling         NA    b    bx21 bx21-iv   1         NA
1918 sapling         NA    b    bx21 bx21-iv   1         NA
1919 sapling         NA    b    bx21 bx21-iv   1         NA
1920 sapling         NA    b    bx21 bx21-iv   1         NA
1921 sapling         NA    b    bx21 bx21-iv   1         NA
1922 sapling         NA    b    bx21 bx21-iv   1         NA
1923 sapling         NA    b    bx21 bx21-iii  1         NA
1924 sapling         NA    b    bv24 bv24-ii   1         NA
1925 sapling         NA    b    bv24 bv24-ii   1         NA
1926 sapling         NA    b    bv24 bv24-ii   1         NA
1927 unknown sapling NA    b    bv24 bv24-iii  1         NA
1928 unknown sapling NA    b    bv24 bv24-iii  1         NA
1929 unknown sapling NA    b    bv24 bv24-iii  1         NA
1930 1315            NA    b    bg28 bg28-iii  2         NA
1931 1375            NA    b    bg28 bg28-iii  2         NA
1932 NA              NA    b    bg28 bg28-iv   2         NA
1933 unknown         NA    b    bg28 bg28-i    2         NA
1934 woody           NA    b    bg28 bg28-i    2         NA
1935 unknown         NA    b    bg28 bg28-i    2         NA
1936 sapling         NA    b    bg28 bg28-i    2         NA
1937 sapling         NA    b    bg28 bg28-i    2         NA
1938 sapling         NA    b    bg28 bg28-i    2         NA
1939 sapling         NA    b    bg28 bg28-i    2         NA
     x8 survival height ⋯ nec_prop percent_nmin percent_nmax
1    v  a        NA     ⋯ NA       NA           NA
2    v  1        70     ⋯ 0        NA           NA
3    v  1        86     ⋯ 0        NA           NA
4    v  s        6      ⋯ 0        NA           NA
5    v  n        52     ⋯ 0        NA           NA
6    v  s        5      ⋯ 0        NA           NA
7    v  1        44     ⋯ 0        NA           NA
8    v  1        86     ⋯ 0        NA           NA
9    v  1        120    ⋯ 0        NA           NA
10   v  1        91     ⋯ 0        NA           NA
11   v  1        103    ⋯ 0        NA           NA
12   v  x        NA     ⋯ NA       NA           NA
13   v  1        88     ⋯ 0        NA           NA
14   v  a        NA     ⋯ NA       NA           NA
15   v  n        39     ⋯ 0        NA           NA
16   v  1        42     ⋯ 0        NA           NA
17   v  d        NA     ⋯ NA       NA           NA
18   v  1        91     ⋯ 0        NA           NA
19   v  a        NA     ⋯ NA       NA           NA
20   v  1        42     ⋯ 0        NA           NA
21   v  1        41     ⋯ 0        NA           NA
22   v  1        45     ⋯ 0        NA           NA
23   v  1        42     ⋯ 0        NA           NA
24   v  a        NA     ⋯ NA       NA           NA
25   v  a        NA     ⋯ NA       NA           NA
26   v  1        73     ⋯ 0        NA           NA
27   v  1        59     ⋯ 0        NA           NA
28   v  r        29     ⋯ 0        NA           NA
29   v  d        NA     ⋯ NA       NA           NA
30   v  a        NA     ⋯ NA       NA           NA
⋮    ⋮  ⋮        ⋮      ⋱ ⋮        ⋮            ⋮
1910 NA d        NA     ⋯ NA       NA           NA
1911 NA NA       12.5   ⋯ NA       NA           NA
1912 NA NA       9      ⋯ NA       NA           NA
1913 NA NA       54     ⋯ NA       NA           NA
1914 NA NA       19     ⋯ NA       NA           NA
1915 NA NA       80     ⋯ NA       NA           NA
1916 NA NA       47     ⋯ NA       NA           NA
1917 NA NA       65     ⋯ NA       NA           NA
1918 NA NA       30     ⋯ NA       NA           NA
1919 NA NA       46     ⋯ NA       NA           NA
1920 NA NA       37     ⋯ NA       NA           NA
1921 NA NA       39     ⋯ NA       NA           NA
1922 NA NA       103    ⋯ NA       NA           NA
1923 NA NA       42     ⋯ NA       NA           NA
1924 NA NA       86     ⋯ NA       NA           NA
1925 NA NA       93     ⋯ NA       NA           NA
1926 NA NA       92.5   ⋯ NA       NA           NA
1927 NA NA       63.5   ⋯ NA       NA           NA
1928 NA NA       43     ⋯ NA       NA           NA
1929 NA NA       39     ⋯ NA       NA           NA
1930 NA NA       55     ⋯ NA       NA           NA
1931 NA NA       54     ⋯ NA       NA           NA
1932 NA NA       NA     ⋯ NA       NA           NA
1933 NA NA       46     ⋯ NA       NA           NA
1934 NA NA       14     ⋯ NA       NA           NA
1935 NA NA       30     ⋯ NA       NA           NA
1936 NA NA       57     ⋯ NA       NA           NA
1937 NA NA       16     ⋯ NA       NA           NA
1938 NA NA       31     ⋯ NA       NA           NA
1939 NA NA       33     ⋯ NA       NA           NA
     notes                   number_herbivory_min number_herbivory_max hmin
1    NA                      NA                   NA                   NA
2    NA                      NA                   NA                   NA
3    NA                      NA                   NA                   NA
4    NA                      NA                   NA                   NA
5    NA                      NA                   NA                   NA
6    NA                      NA                   NA                   NA
7    NA                      NA                   NA                   NA
8    NA                      NA                   NA                   NA
9    NA                      NA                   NA                   NA
10   NA                      NA                   NA                   NA
11   largely outside plot    NA                   NA                   NA
12   same individual as 1740 NA                   NA                   NA
13   new label, was 775.; 5b NA                   NA                   NA
14   NA                      NA                   NA                   NA
15   NA                      NA                   NA                   NA
16   NA                      NA                   NA                   NA
17   NA                      NA                   NA                   NA
18   NA                      NA                   NA                   NA
19   NA                      NA                   NA                   NA
20   NA                      NA                   NA                   NA
21   NA                      NA                   NA                   NA
22   NA                      NA                   NA                   NA
23   4b                      NA                   NA                   NA
24   NA                      NA                   NA                   NA
25   NA                      NA                   NA                   NA
26   NA                      NA                   NA                   NA
27   4b                      NA                   NA                   NA
28   leavs from 35 to 100    NA                   NA                   NA
29   NA                      NA                   NA                   NA
30   NA                      NA                   NA                   NA
⋮    ⋮                       ⋮                    ⋮                    ⋮
1910 NA                      NA                   NA                   NA
1911 NA                      NA                   NA                   NA
1912 NA                      0                    NA                   0
1913 NA                      3                    NA                   2
1914 NA                      1                    NA                   40
1915 NA                      25                   NA                   5
1916 NA                      12                   NA                   1
1917 NA                      29                   NA                   1
1918 NA                      25                   NA                   5
1919 NA                      8                    NA                   1
1920 NA                      43                   NA                   5
1921 NA                      3                    NA                   2
1922 NA                      29                   NA                   5
1923 NA                      20                   NA                   5
1924 NA                      36                   NA                   2
1925 NA                      34                   NA                   5
1926 NA                      32                   NA                   2
1927 NA                      7                    NA                   5
1928 NA                      2                    NA                   10
1929 NA                      29                   NA                   10
1930 NA                      5                    NA                   1
1931 NA                      82                   NA                   1
1932 NA                      NA                   NA                   NA
1933 NA                      NA                   NA                   NA
1934 NA                      NA                   NA                   NA
1935 NA                      3                    NA                   1
1936 NA                      4                    NA                   2
1937 NA                      NA                   NA                   40
1938 NA                      NA                   NA                   2
1939 NA                      NA                   NA                   5
     hmax fmin fmax
1    NA   NA   NA
2    NA   NA   NA
3    NA   NA   NA
4    NA   NA   NA
5    NA   NA   NA
6    NA   NA   NA
7    NA   NA   NA
8    NA   NA   NA
9    NA   NA   NA
10   NA   NA   NA
11   NA   NA   NA
12   NA   NA   NA
13   NA   NA   NA
14   NA   NA   NA
15   NA   NA   NA
16   NA   NA   NA
17   NA   NA   NA
18   NA   NA   NA
19   NA   NA   NA
20   NA   NA   NA
21   NA   NA   NA
22   NA   NA   NA
23   NA   NA   NA
24   NA   NA   NA
25   NA   NA   NA
26   NA   NA   NA
27   NA   NA   NA
28   NA   NA   NA
29   NA   NA   NA
30   NA   NA   NA
⋮    ⋮    ⋮    ⋮
1910 NA   NA   NA
1911 NA   NA   NA
1912 NA   NA   NA
1913 60   5    20
1914 NA   100  100
1915 40   5    5
1916 25   5    20
1917 50   1    50
1918 80   1    5
1919 25   5    15
1920 85   1    15
1921 20   NA   NA
1922 40   NA   NA
1923 60   NA   NA
1924 40   NA   NA
1925 60   NA   NA
1926 55   NA   NA
1927 55   10   19
1928 15   NA   NA
1929 90   NA   NA
1930 20   1    20
1931 80   1    20
1932 NA   NA   NA
1933 NA   NA   NA
1934 NA   NA   NA
1935 15   NA   NA
1936 5    NA   NA
1937 NA   NA   NA
1938 20   10   30
1939 50   1    30

In [414]:
final_joined <- read.csv('datas_and_notebooks/final_datas/final_joined.csv') |> 
 select(-X)
final_joined |> 
 str()

'data.frame':	2160 obs. of  42 variables:
 $ date                   : chr  "2023-09-07" "2023-09-07" "2023-09-07" "2023-09-07" ...
 $ site                   : chr  "a" "a" "a" "a" ...
 $ plot                   : chr  "ae31" "ae31" "ae31" "ae31" ...
 $ subplot                : chr  "ae31-i" "ae31-i" "ae31-ii" "ae31-iii" ...
 $ diversity              : int  1 1 1 1 1 1 1 1 1 1 ...
 $ id                     : chr  "340" "92" "250" "248" ...
 $ species                : chr  "quercus serrata" "quercus serrata" "dalbergia hupeana" "rhododendron simsii" ...
 $ genus                  : chr  "quercus" "quercus" "dalbergia" "rhododendron" ...
 $ family                 : chr  "fagaceae" "fagaceae" "fabaceae" "ericaceae" ...
 $ growth_form            : chr  "tree" "tree" "tree" "shrub/tree" ...
 $ seed_source_short      : chr  "II" "II" "EI" "ASP" ...
 $ type                   : chr  NA "sapling" "sapling" "sapling" ...
 $ survival               : chr  "d" "1" "1" "1" ...
 $ height                 : int  NA 38 79 43 11 48 47 38 NA 53 ...
 $ number_leaves          : int  NA 16 5 8 2 120 37 62 NA 120 ...
 $ number_herb_damaged    : int  NA 2 5 5 0 16 20 7 NA 4 ...
 $ number_fungal_damaged  : int  NA 0 0 0 0 0 35 60 NA 8 ...
 $ number_necrotic_damaged: int  NA 7 4 8 0 12 0 0 NA 0 ...
 $ percent_hmin           : num  NA 0.01 0.05 0.05 NA 0.05 0.05 0.01 NA 0.01 ...
 $ percent_hmax           : num  NA 0.05 0.8 0.4 NA 0.8 0.7 0.05 NA 0.05 ...
 $ percent_fmin           : num  NA NA NA NA NA NA 0.01 0.01 NA 0.1 ...
 $ percent_fmax           : num  NA NA NA NA NA NA 0.4 0.9 NA 0.5 ...
 $ percent_nmin           : num  NA 0.01 0.03 0.01 NA 0.01 NA NA NA NA ...
 $ percent_nmax           : num  NA 0.1 0.1 0.7 NA 0.1 NA NA NA NA ...
 $ month                  : int  9 9 9 9 9 9 9 9 9 9 ...
 $ year                   : int  2023 2023 2023 2023 2023 2023 2023 2023 2023 2023 ...
 $ percent_herb           : num  NA 0.125 1 0.625 0 ...
 $ percent_necrose        : num  NA 0.438 0.8 1 0 ...
 $ percent_fungal         : num  NA 0 0 0 0 ...
 $ notes                  : chr  "internal invader" "internal invader" "external invader" "planted, but not at this site" ...
 $ tot_veg                : num  0.05 0.05 0.1 0.4 0.4 0.4 0.4 0.4 0.05 0.05 ...
 $ herb_max               : int  20 20 35 39 39 39 39 39 27 27 ...
 $ grass                  : num  0.001 0.001 0 0.001 0.001 0.001 0.001 0.001 0.001 0.001 ...
 $ fern                   : num  0.01 0.01 0.05 0.05 0.05 0.05 0.05 0.05 0.001 0.001 ...
 $ herbaceous             : num  0.001 0.001 0.01 0.001 0.001 0.001 0.001 0.001 0.001 0.001 ...
 $ woody                  : num  0.02 0.02 0.05 0.35 0.35 0.35 0.35 0.35 0.01 0.01 ...
 $ rock                   : num  0 0 0 0 0 0 0 0 0 0 ...
 $ deadwood               : num  0.05 0.05 0.02 0.001 0.001 0.001 0.001 0.001 0.001 0.001 ...
 $ leaflitter             : num  0.2 0.2 0.4 0.5 0.5 0.5 0.5 0.5 0.05 0.05 ...
 $ moss                   : num  0.02 0.02 0.001 0.01 0.01 0.01 0.01 0.01 0.001 0.001 ...
 $ saplings               : int  2 2 1 6 6 6 6 6 5 5 ...
 $ seedlings              : int  10 10 12 4 4 4 4 4 6 6 ...

In [416]:
library(dplyr)
library(tidyr)
library(stringr)
library(purrr)

surveys_24_updated <- surveys_24 |> 
  left_join(final_joined |> distinct(id, plot, subplot, species2 = species, diversity2 = diversity, family, genus, growth_form, seed_source_short )) |> 
  mutate(
    species = if_else(is.na(species) & !is.na(species2), species2, species)
  ) |> 
  select(-species2, x8) |> 
  filter(!is.na(id)) |> 
  mutate(
    number_necrosis = stringr::str_replace(number_necrosis, "/", ""),
    number_fungal_pathogen_damaged = stringr::str_replace(number_fungal_pathogen_damaged, "0/", "0"), 
    subplot = stringr::str_replace(subplot, "bu16- iv", "bu16-iv"),
    diversity = stringr::str_replace_all(diversity, "226", "1"), 
    subplot = stringr::str_replace_all(subplot, "ar33.ii", "ae33.ii")
  ) |> 
  mutate(
    number_herbivory_min = if_else(
      is.na(number_herbivory_min) & !is.na(hmin), hmin, number_herbivory_min
    ),
    number_herbivory_max = if_else(
      is.na(number_herbivory_max) & !is.na(hmax), hmax, number_herbivory_max
    )
  ) |> 
  select(-c(hmax, hmin)) |> 
  group_by(plot, subplot) |> 
  mutate(
    diversity2 = if_else(
      is.na(diversity2) & any(!is.na(diversity2)), 
      unique(na.omit(diversity2))[1], 
      diversity2
    )
  ) |> 
  mutate(
    diversity2 = if_else(
      is.na(diversity2) & !is.na(diversity), as.character(diversity), as.character(diversity2)
    )
  ) |> 
  ungroup() |> 
  mutate(
    diversity2 = if_else(
      stringr::str_detect(subplot, "ae33.ii|ai28.iv"), "1", diversity2
    )
  ) |> 
  select(date, plot, subplot, id, species, everything(), -diversity, -x8) |> 
  rename("diversity" = diversity2) |> 
  mutate(
    height = as.numeric(height),
    leaves = as.numeric(leaves),
    number_herbivory_damaged = as.numeric(number_herbivory_damaged),
    hprop = as.numeric(hprop),
    percent_hmin = as.numeric(percent_hmin),
    percent_hmax = as.numeric(percent_hmax),
    number_fungal_pathogen_damaged = as.numeric(number_fungal_pathogen_damaged),
    fprop = as.numeric(fprop),
    percent_fmin = as.numeric(percent_fmin),
    percent_fmax = as.numeric(percent_fmax),
    number_necrosis = as.numeric(number_necrosis),
    nec_prop = as.numeric(nec_prop),
    percent_nmin = as.numeric(percent_nmin),
    percent_nmax = as.numeric(percent_nmax),
    number_herbivory_min = as.numeric(number_herbivory_min),
    number_herbivory_max = as.numeric(number_herbivory_max),
    fmin = as.numeric(fmin),
    fmax = as.numeric(fmax)
  )

# Define a named vector of corrections: wrong = right
species_corrections <- c(
  "camellia sinesis" = "camellia sinensis",
  "camellia sp," = "camellia sp.",
  "quercus sp," = "quercus sp.",
  "seedming" = "seedling",
  "seedlig" = "seedling",
  "machilus grijsi" = "machilus grijesi",
  "machilus grijesi'" = "machilus grijesi",
  "lindera reflexa'" = "lindera reflexa",
  "camellia fra'trema cannabina" = "camellia fra'trema cannabina", # unclear, left as is
  "herb'" = "herb",
  "rosa sp.'" = "rosa sp.",
  "camellia sp.''" = "camellia sp.",
  "camellia sp." = "camellia sp.",
  "quercus seedling" = "seedling",
  "woody recruit" = "recruit",
  "seedling (cfr. litsea)" = "seedling"
)

# Clean up species names
surveys_24_updated <- surveys_24_updated %>%
  mutate(
    species = str_trim(species),
    species = str_to_lower(species),
    species = str_replace_all(species, "[‘’'`]", ""), # remove stray quotes
    species = str_replace_all(species, "\\s+", " "),  # collapse multiple spaces
    species = str_replace(species, ",$", "."),        # replace trailing comma with period
    species = if_else(species %in% names(species_corrections), species_corrections[species], species),
    species = if_else(species %in% c("na", "", "unknown sp.", "look at photo", "not-liquidambar", "444", "1171", "307"), NA_character_, species)
  )

surveys_24_updated |> 
  str()

Joining with `by = join_by(id, plot, subplot)`
Warning message in left_join(surveys_24, distinct(final_joined, id, plot, subplot, :
“Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 1 of `x` matches multiple rows in `y`.
ℹ Row 512 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.”
Warning message:
“There were 10 warnings in `mutate()`.
The first warning was:
ℹ In argument: `height = as.numeric(height)`.
Caused by warning:
! NAs introduced by coercion
ℹ Run `dplyr::last_dplyr_warnings()` to see the 9 remaining warnings.”

tibble [2,646 × 31] (S3: tbl_df/tbl/data.frame)
 $ date                          : chr [1:2646] "45438" "45438" "45438" "45438" ...
 $ plot                          : chr [1:2646] "ac32" "ac32" "ac32" "ac32" ...
 $ subplot                       : chr [1:2646] "ac32-i" "ac32-i" "ac32-i" "ac32-i" ...
 $ id                            : chr [1:2646] "276" "276" "327" "327" ...
 $ species                       : Named chr [1:2646] "lindera reflexa" "lindera reflexa" "lindera reflexa" "lindera reflexa" ...
  ..- attr(*, "names")= chr [1:2646] "" "" "" "" ...
 $ site                          : chr [1:2646] "a" "a" "a" "a" ...
 $ survival                      : chr [1:2646] "a" "a" "1" "1" ...
 $ height                        : num [1:2646] NA NA 70 70 86 86 6 52 5 44 ...
 $ leaves                        : num [1:2646] NA NA 93 93 250 250 6 17 2 59 ...
 $ number_herbivory_damaged      : num [1:2646] NA NA 14 14 0 0 3 12 0 24 ...
 $ hprop                         : num [1:2646] NA NA 0.151 0.151 0 ...
 $ percent_hmin                  : num [1:2646] NA NA 0.01 0.01 NA NA 0.2 0.05 NA 0.01 ...
 $ percent_hmax                  : num [1:2646] NA NA 0.5 0.5 NA NA 0.3 0.3 NA 0.55 ...
 $ number_fungal_pathogen_damaged: num [1:2646] NA NA 9 9 3 3 0 6 0 3 ...
 $ fprop                         : num [1:2646] NA NA 0.0968 0.0968 0.012 ...
 $ percent_fmin                  : num [1:2646] NA NA 0.01 0.01 0.05 0.05 NA 0.05 NA 0.01 ...
 $ percent_fmax                  : num [1:2646] NA NA 0.45 0.45 0.15 0.15 NA 0.05 NA 0.4 ...
 $ number_necrosis               : num [1:2646] NA NA 0 0 0 0 0 0 0 0 ...
 $ nec_prop                      : num [1:2646] NA NA 0 0 0 0 0 0 0 0 ...
 $ percent_nmin                  : num [1:2646] NA NA NA NA NA NA NA NA NA NA ...
 $ percent_nmax                  : num [1:2646] NA NA NA NA NA NA NA NA NA NA ...
 $ notes                         : chr [1:2646] NA NA NA NA ...
 $ number_herbivory_min          : num [1:2646] NA NA NA NA NA NA NA NA NA NA ...
 $ number_herbivory_max          : num [1:2646] NA NA NA NA NA NA NA NA NA NA ...
 $ fmin                          : num [1:2646] NA NA NA NA NA NA NA NA NA NA ...
 $ fmax                          : num [1:2646] NA NA NA NA NA NA NA NA NA NA ...
 $ diversity                     : chr [1:2646] "2" "2" "2" "2" ...
 $ family                        : chr [1:2646] "lauraceae" "lauraceae" "lauraceae" "lauraceae" ...
 $ genus                         : chr [1:2646] "lindera" "lindera" "lindera" "lindera" ...
 $ growth_form                   : chr [1:2646] "shrub/tree" "shrub/tree" "shrub/tree" "shrub/tree" ...
 $ seed_source_short             : chr [1:2646] "EI" NA "EI" NA ...

In [417]:
surveys_24_updated <- surveys_24_updated |>
  rename(
    "number_leaves" = leaves,
    "number_fungal_damaged" = number_fungal_pathogen_damaged,
    "number_necrotic_damaged" = number_necrosis,
    "percent_necrose" = nec_prop,
	  "number_herb_damaged" = number_herbivory_damaged,
    "percent_fungal" = fprop
  ) |>
  mutate(
    percent_hmin = ifelse(
      is.na(percent_hmin) & !is.na(number_herbivory_min) & !is.na(number_leaves),
      as.numeric(number_herbivory_min) / as.numeric(number_leaves),
      as.numeric(percent_hmin)
    ),
    percent_hmax = ifelse(
      is.na(percent_hmax) & !is.na(number_herbivory_max) & !is.na(number_leaves),
      as.numeric(number_herbivory_max) / as.numeric(number_leaves),
      as.numeric(percent_hmax)
    ),
    percent_fmin = ifelse(
      is.na(percent_fmin) & !is.na(fmin) & !is.na(number_leaves),
      as.numeric(fmin) / as.numeric(number_leaves),
      as.numeric(percent_fmin)
    ),
    percent_fmax = ifelse(
      is.na(percent_fmax) & !is.na(fmax) & !is.na(number_leaves),
      as.numeric(fmax) / as.numeric(number_leaves),
      as.numeric(percent_fmax)
    )
  ) |> 
 select(-c(fmin, fmax, hprop)) |> 
 mutate(year = as.integer(paste("2024")))
surveys_24_updated |> 
 str()

tibble [2,646 × 29] (S3: tbl_df/tbl/data.frame)
 $ date                   : chr [1:2646] "45438" "45438" "45438" "45438" ...
 $ plot                   : chr [1:2646] "ac32" "ac32" "ac32" "ac32" ...
 $ subplot                : chr [1:2646] "ac32-i" "ac32-i" "ac32-i" "ac32-i" ...
 $ id                     : chr [1:2646] "276" "276" "327" "327" ...
 $ species                : Named chr [1:2646] "lindera reflexa" "lindera reflexa" "lindera reflexa" "lindera reflexa" ...
  ..- attr(*, "names")= chr [1:2646] "" "" "" "" ...
 $ site                   : chr [1:2646] "a" "a" "a" "a" ...
 $ survival               : chr [1:2646] "a" "a" "1" "1" ...
 $ height                 : num [1:2646] NA NA 70 70 86 86 6 52 5 44 ...
 $ number_leaves          : num [1:2646] NA NA 93 93 250 250 6 17 2 59 ...
 $ number_herb_damaged    : num [1:2646] NA NA 14 14 0 0 3 12 0 24 ...
 $ percent_hmin           : num [1:2646] NA NA 0.01 0.01 NA NA 0.2 0.05 NA 0.01 ...
 $ percent_hmax           : num [1:2646] NA NA 0.5 0.5 NA NA 0.3 0.3 NA 0.55 ...
 $ number_fungal_damaged  : num [1:2646] NA NA 9 9 3 3 0 6 0 3 ...
 $ percent_fungal         : num [1:2646] NA NA 0.0968 0.0968 0.012 ...
 $ percent_fmin           : num [1:2646] NA NA 0.01 0.01 0.05 0.05 NA 0.05 NA 0.01 ...
 $ percent_fmax           : num [1:2646] NA NA 0.45 0.45 0.15 0.15 NA 0.05 NA 0.4 ...
 $ number_necrotic_damaged: num [1:2646] NA NA 0 0 0 0 0 0 0 0 ...
 $ percent_necrose        : num [1:2646] NA NA 0 0 0 0 0 0 0 0 ...
 $ percent_nmin           : num [1:2646] NA NA NA NA NA NA NA NA NA NA ...
 $ percent_nmax           : num [1:2646] NA NA NA NA NA NA NA NA NA NA ...
 $ notes                  : chr [1:2646] NA NA NA NA ...
 $ number_herbivory_min   : num [1:2646] NA NA NA NA NA NA NA NA NA NA ...
 $ number_herbivory_max   : num [1:2646] NA NA NA NA NA NA NA NA NA NA ...
 $ diversity              : chr [1:2646] "2" "2" "2" "2" ...
 $ family                 : chr [1:2646] "lauraceae" "lauraceae" "lauraceae" "lauraceae" ...
 $ genus                  : chr [1:2646] "lindera" "lindera" "lindera" "lindera" ...
 $ growth_form            : chr [1:2646] "shrub/tree" "shrub/tree" "shrub/tree" "shrub/tree" ...
 $ seed_source_short      : chr [1:2646] "EI" NA "EI" NA ...
 $ year                   : int [1:2646] 2024 2024 2024 2024 2024 2024 2024 2024 2024 2024 ...

In [418]:
library(readxl)
library(stringr)
library(dplyr)

surveys_all <- read_excel("datas_and_notebooks/2024/Vegetation survey spring 2024 (1 subplot missing).xlsx") |> 
  janitor::clean_names() |> 
  mutate(across(everything(), ~ if(is.character(.)) str_trim(tolower(.)) else .)) |>
  select(-contains("spalte")) |>
  rename(
    "herb_max" = max_herb_layer_height,
    "deadwood" = deadwppd, 
	  "woody" = "woody_plants", 
	  "leaflitter_dept" = leaf_litter_dept, 
	  "leaflitter" = leaf_litter, 
	  "herbaceous" = herb
  ) |>
  mutate(across(4:15, as.numeric)) |> 
  full_join(
    surveys_24_updated |> 
      rename("notes2" = notes) |>  
      select(-date) |> 
      mutate(diversity = as.integer(diversity))
  ) |> 
  distinct() |> 
  select(    date, site, plot, subplot, diversity, id, species, genus, family, growth_form, seed_source_short,
    everything()
  ) |> 
				select(-c(number_herbivory_min, number_herbivory_max)) |> 
				select(everything(), notes, notes2) |> 
				full_join(final_joined |> 
						 mutate(date = as.Date(date))) 

surveys_all |> 
  str()

Warning message:
“There were 12 warnings in `mutate()`.
The first warning was:
ℹ In argument: `across(4:15, as.numeric)`.
Caused by warning:
! NAs introduced by coercion
ℹ Run `dplyr::last_dplyr_warnings()` to see the 11 remaining warnings.”
Joining with `by = join_by(plot, subplot)`
Warning message in full_join(mutate(rename(select(mutate(janitor::clean_names(read_excel("datas_and_notebooks/2024/Vegetation survey spring 2024 (1 subplot missing).xlsx")), :
“Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 1 of `x` matches multiple rows in `y`.
ℹ Row 478 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.”
Joining with `by = join_by(date, site, plot, subplot, diversity, id, species,
genus, family, growth_form, seed_source_short, tot_veg, herb_max, grass, fern,
herbaceous, woody, rock, leaflitter, deadwood, moss, notes, survival, height,
number_leaves, number_herb_damaged, percent_hmin, percent_hmax,
number_fungal_damaged, percent_fungal, percent_fmin, percent_fmax,
number_necrotic_damaged, percent_necrose, percent_nmin, percent_nmax, year)`

tibble [4,833 × 45] (S3: tbl_df/tbl/data.frame)
 $ date                   : POSIXct[1:4833], format: "2024-05-26" "2024-05-26" ...
 $ site                   : chr [1:4833] "a" "a" "a" "a" ...
 $ plot                   : chr [1:4833] "ac32" "ac32" "ac32" "ac32" ...
 $ subplot                : chr [1:4833] "ac32-i" "ac32-i" "ac32-i" "ac32-i" ...
 $ diversity              : int [1:4833] 2 2 2 2 2 2 2 2 2 2 ...
 $ id                     : chr [1:4833] "276" "276" "327" "327" ...
 $ species                : Named chr [1:4833] "lindera reflexa" "lindera reflexa" "lindera reflexa" "lindera reflexa" ...
  ..- attr(*, "names")= chr [1:4833] "" "" "" "" ...
 $ genus                  : chr [1:4833] "lindera" "lindera" "lindera" "lindera" ...
 $ family                 : chr [1:4833] "lauraceae" "lauraceae" "lauraceae" "lauraceae" ...
 $ growth_form            : chr [1:4833] "shrub/tree" "shrub/tree" "shrub/tree" "shrub/tree" ...
 $ seed_source_short      : chr [1:4833] "EI" NA "EI" NA ...
 $ tot_veg                : num [1:4833] 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.65 ...
 $ herb_max               : num [1:4833] 72 72 72 72 72 72 72 72 72 71 ...
 $ grass                  : num [1:4833] 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0 ...
 $ fern                   : num [1:4833] 0 0 0 0 0 0 0 0 0 0.1 ...
 $ herbaceous             : num [1:4833] 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.35 ...
 $ woody                  : num [1:4833] 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.2 ...
 $ open_ground            : num [1:4833] 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.25 ...
 $ rock                   : num [1:4833] 0 0 0 0 0 0 0 0 0 0.01 ...
 $ leaflitter             : num [1:4833] 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.05 ...
 $ leaflitter_dept        : num [1:4833] 1 1 1 1 1 1 1 1 1 1 ...
 $ deadwood               : num [1:4833] 0 0 0 0 0 0 0 0 0 0 ...
 $ moss                   : num [1:4833] 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.05 ...
 $ notes                  : chr [1:4833] "big cunninghamia right in the middle (128cm high)" "big cunninghamia right in the middle (128cm high)" "big cunninghamia right in the middle (128cm high)" "big cunninghamia right in the middle (128cm high)" ...
 $ survival               : chr [1:4833] "a" "a" "1" "1" ...
 $ height                 : num [1:4833] NA NA 70 70 86 86 6 52 5 44 ...
 $ number_leaves          : num [1:4833] NA NA 93 93 250 250 6 17 2 59 ...
 $ number_herb_damaged    : num [1:4833] NA NA 14 14 0 0 3 12 0 24 ...
 $ percent_hmin           : num [1:4833] NA NA 0.01 0.01 NA NA 0.2 0.05 NA 0.01 ...
 $ percent_hmax           : num [1:4833] NA NA 0.5 0.5 NA NA 0.3 0.3 NA 0.55 ...
 $ number_fungal_damaged  : num [1:4833] NA NA 9 9 3 3 0 6 0 3 ...
 $ percent_fungal         : num [1:4833] NA NA 0.0968 0.0968 0.012 ...
 $ percent_fmin           : num [1:4833] NA NA 0.01 0.01 0.05 0.05 NA 0.05 NA 0.01 ...
 $ percent_fmax           : num [1:4833] NA NA 0.45 0.45 0.15 0.15 NA 0.05 NA 0.4 ...
 $ number_necrotic_damaged: num [1:4833] NA NA 0 0 0 0 0 0 0 0 ...
 $ percent_necrose        : num [1:4833] NA NA 0 0 0 0 0 0 0 0 ...
 $ percent_nmin           : num [1:4833] NA NA NA NA NA NA NA NA NA NA ...
 $ percent_nmax           : num [1:4833] NA NA NA NA NA NA NA NA NA NA ...
 $ notes2                 : chr [1:4833] NA NA NA NA ...
 $ year                   : int [1:4833] 2024 2024 2024 2024 2024 2024 2024 2024 2024 2024 ...
 $ type                   : chr [1:4833] NA NA NA NA ...
 $ month                  : int [1:4833] NA NA NA NA NA NA NA NA NA NA ...
 $ percent_herb           : num [1:4833] NA NA NA NA NA NA NA NA NA NA ...
 $ saplings               : int [1:4833] NA NA NA NA NA NA NA NA NA NA ...
 $ seedlings              : int [1:4833] NA NA NA NA NA NA NA NA NA NA ...

In [419]:
surveys_all |> 
 write.csv("datas_and_notebooks/final_datas/all_data_joined.csv", row.names = F)

In [420]:
final_joined |> 
  str()

'data.frame':	2160 obs. of  42 variables:
 $ date                   : chr  "2023-09-07" "2023-09-07" "2023-09-07" "2023-09-07" ...
 $ site                   : chr  "a" "a" "a" "a" ...
 $ plot                   : chr  "ae31" "ae31" "ae31" "ae31" ...
 $ subplot                : chr  "ae31-i" "ae31-i" "ae31-ii" "ae31-iii" ...
 $ diversity              : int  1 1 1 1 1 1 1 1 1 1 ...
 $ id                     : chr  "340" "92" "250" "248" ...
 $ species                : chr  "quercus serrata" "quercus serrata" "dalbergia hupeana" "rhododendron simsii" ...
 $ genus                  : chr  "quercus" "quercus" "dalbergia" "rhododendron" ...
 $ family                 : chr  "fagaceae" "fagaceae" "fabaceae" "ericaceae" ...
 $ growth_form            : chr  "tree" "tree" "tree" "shrub/tree" ...
 $ seed_source_short      : chr  "II" "II" "EI" "ASP" ...
 $ type                   : chr  NA "sapling" "sapling" "sapling" ...
 $ survival               : chr  "d" "1" "1" "1" ...
 $ height                 : int  NA 38 79 43 11 48 47 38 NA 53 ...
 $ number_leaves          : int  NA 16 5 8 2 120 37 62 NA 120 ...
 $ number_herb_damaged    : int  NA 2 5 5 0 16 20 7 NA 4 ...
 $ number_fungal_damaged  : int  NA 0 0 0 0 0 35 60 NA 8 ...
 $ number_necrotic_damaged: int  NA 7 4 8 0 12 0 0 NA 0 ...
 $ percent_hmin           : num  NA 0.01 0.05 0.05 NA 0.05 0.05 0.01 NA 0.01 ...
 $ percent_hmax           : num  NA 0.05 0.8 0.4 NA 0.8 0.7 0.05 NA 0.05 ...
 $ percent_fmin           : num  NA NA NA NA NA NA 0.01 0.01 NA 0.1 ...
 $ percent_fmax           : num  NA NA NA NA NA NA 0.4 0.9 NA 0.5 ...
 $ percent_nmin           : num  NA 0.01 0.03 0.01 NA 0.01 NA NA NA NA ...
 $ percent_nmax           : num  NA 0.1 0.1 0.7 NA 0.1 NA NA NA NA ...
 $ month                  : int  9 9 9 9 9 9 9 9 9 9 ...
 $ year                   : int  2023 2023 2023 2023 2023 2023 2023 2023 2023 2023 ...
 $ percent_herb           : num  NA 0.125 1 0.625 0 ...
 $ percent_necrose        : num  NA 0.438 0.8 1 0 ...
 $ percent_fungal         : num  NA 0 0 0 0 ...
 $ notes                  : chr  "internal invader" "internal invader" "external invader" "planted, but not at this site" ...
 $ tot_veg                : num  0.05 0.05 0.1 0.4 0.4 0.4 0.4 0.4 0.05 0.05 ...
 $ herb_max               : int  20 20 35 39 39 39 39 39 27 27 ...
 $ grass                  : num  0.001 0.001 0 0.001 0.001 0.001 0.001 0.001 0.001 0.001 ...
 $ fern                   : num  0.01 0.01 0.05 0.05 0.05 0.05 0.05 0.05 0.001 0.001 ...
 $ herbaceous             : num  0.001 0.001 0.01 0.001 0.001 0.001 0.001 0.001 0.001 0.001 ...
 $ woody                  : num  0.02 0.02 0.05 0.35 0.35 0.35 0.35 0.35 0.01 0.01 ...
 $ rock                   : num  0 0 0 0 0 0 0 0 0 0 ...
 $ deadwood               : num  0.05 0.05 0.02 0.001 0.001 0.001 0.001 0.001 0.001 0.001 ...
 $ leaflitter             : num  0.2 0.2 0.4 0.5 0.5 0.5 0.5 0.5 0.05 0.05 ...
 $ moss                   : num  0.02 0.02 0.001 0.01 0.01 0.01 0.01 0.01 0.001 0.001 ...
 $ saplings               : int  2 2 1 6 6 6 6 6 5 5 ...
 $ seedlings              : int  10 10 12 4 4 4 4 4 6 6 ...

In [421]:
# Corrected code
data.frame(Column_Names = colnames(final_joined))

   Column_Names
1  date
2  site
3  plot
4  subplot
5  diversity
6  id
7  species
8  genus
9  family
10 growth_form
11 seed_source_short
12 type
13 survival
14 height
15 number_leaves
16 number_herb_damaged
17 number_fungal_damaged
18 number_necrotic_damaged
19 percent_hmin
20 percent_hmax
21 percent_fmin
22 percent_fmax
23 percent_nmin
24 percent_nmax
25 month
26 year
27 percent_herb
28 percent_necrose
29 percent_fungal
30 notes
31 tot_veg
32 herb_max
33 grass
34 fern
35 herbaceous
36 woody
37 rock
38 deadwood
39 leaflitter
40 moss
41 saplings
42 seedlings

In [422]:
library(dplyr)
library(stringr)
library(purrr)


# Show unique species after cleaning
unique_species <- surveys_24_updated %>%
  distinct(species) %>%
  arrange(species)

unique_species

   species
1  actinidia melanandra
2  actinidia polygama
3  adinandra millettii
4  ailanthus altissima
5  albizia julibrissin
6  alniphyllum fortunei
7  aralia chinensis
8  ardisia crenata
9  betula luminifera
10 broussonetia papyrifera
11 buddleja lindleyana
12 calicarpa dichotoma
13 calicarpa giraldii
14 calicarpa rubella
15 calicarpa sp.
16 camellia
17 camellia fraterna
18 camellia japonica
19 camellia seedling
20 camellia sinensis
21 camellia sp.
22 castanea henryi
23 castanopsis fargesii
24 castanopsis sclerophylla
25 cinnamomum camphora
26 clerodendrum cyrtophyllum
27 crataegus cuneata
28 dalbergia hupeana
29 distylium buxifolium
30 euonymus maxiflorus
⋮  ⋮
54 nyssa sinensis
55 osmanthus fragrans
56 photinia hirsuta
57 phyllostachys glauca
58 premna microphylla
59 pterostyrax corymbosus
60 quercus fabri
61 quercus phillyreoides
62 quercus serrata
63 quercus sp.
64 recruit
65 rhaphiolepis indica
66 rhododendron simsii
67 rhus chinensis
68 rosa
69 rosa sp.
70 rubus corchorifolius
71 schoepfia jasminodora
72 seedling
73 smilax china
74 smilax glabra
75 styrax odoratissmus
76 symplocos anomala
77 symplocos stellaris
78 syzygium buxifolium
79 toxicodendron succedaneum
80 trema cannabina
81 vaccinium bracteatum
82 viburnum setigerum
83 NA