In [1]:
library(tidyverse)
library(readxl)

# Get all sheet names for each file
sheets_a <- excel_sheets("datas_and_notebooks/soil_data/SP6_Site_A_CNS_pH_depth_increments-2.xls")
sheets_b <- excel_sheets("datas_and_notebooks/soil_data/SP6_Site_B_CNS_pH_depth_increments.xls")

# Read all sheets into a named list of dataframes for each file
site_a_list <- setNames(
  lapply(sheets_a, function(s) read_excel("datas_and_notebooks/soil_data/SP6_Site_A_CNS_pH_depth_increments-2.xls", sheet = s)),
  sheets_a
)

site_b_list <- setNames(
  lapply(sheets_b, function(s) read_excel("datas_and_notebooks/soil_data/SP6_Site_B_CNS_pH_depth_increments.xls", sheet = s)),
  sheets_b
)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
New names:
• `` -> `...3`
• `` -> `...4`
New names:
• `` -> `...3`
• `` -> `...4`

In [2]:
clean_df <- function(df) {
  df %>%
    janitor::clean_names() %>%
    dplyr::mutate(across(
      where(is.character),
      ~ stringr::str_trim(tolower(.))
    ))
}

In [3]:
a_soils <- site_a_list$'Raw data' |> 
 clean_df()

In [4]:
b_soils <- site_b_list$`Raw data` |> 
 clean_df()

In [5]:
site_a_list$`Columns and data groups`

   Column Header
1  plot_number
2  PTAG
3  sample_num
4  lab_num
5  depth_lb
6  pH_H2O
7  pH_KCl
8  N_t
9  C_t
10 S_t
11 C_N
   Column Definition
1  Plot Letter Code; Datagroup description: Plot name (letter, number code)
2  plot code, BEF research plot name, 6 digits with "p" in front; Datagroup description: Research plots of the Biodiversity - Ecosystem functioning experiment (BEF-China). Main Experiment plots have a size of 1 mu, which is about 25x25m^2 in horizontal projection. Pilot Study Plots have a size of 1x1 m^2. Research plots on the main experiment have a "p" in front of their IDs and then a 6 digit code: Plots in the main sites A and B are named according to their position in the original spreadsheet, in which they were designed. They consist of 6 digits: _1st digit_: Site (1:A, 2:B), _digit 2and3_: southwards row: as in spreadsheets the rows are named from the top to the bottom; _digit 4 and 5_: westward column: as in the original spreadsheet, but the letters are converted to numbers (A=01, B=02); _6th digit_: indicator, if the plot has been shifted a quarter mu. Example: "p205260": "p" means that this is a plot that is specified. "2" means, that we are at site B. Now the coordinates of the south - west corner: "0526". Since "e" is the fifth letter of the alphabet, this is Plot E26. The last digit "0" means that this plot was not moved by a quarter of a Mu, as some sites in Site B. The 6th digit can also indicate the subplot within the plot. "5", "6", "7", "8" indicate the northwest, northeast, southeast, and southwest quarter plot respectively.; Datagroup description: Research plots of the Biodiversity - Ecosystem functioning experiment (BEF-China). There are three main sites for research plots in the BEF Experiment: Comparative Study Plots (CSP) in the Gutianshan Nature Reserve (29º8'18" – 29º17'29" N, 118º2'14" – 118º11'12" E, Zhejiang Province Southeast China), having a size of 30x30m^2, measured on the ground. Main Experiment plots have a size of 1 mu, which is about 25x25m^2 in horizontal projection. Pilot Study Plots have a size of 1x1 m^2. Research plots on the main experiment have a "p" in front of their IDs and then a 6 digit code: Plots in the main sites A (29°07'28.2"N 117°54'27.5"E) and B (29°05'06.8"N 117°55'44.4"E) are named according to their position in the original spreadsheet, in which they were designed. They consist of 6 digits: _1st digit_: Site (1:A, 2:B), _digit 2and3_: southwards row: as in spreadsheets the rows are named from the top to the bottom; _digit 4 and 5_: westward column: as in the original spreadsheet, but the letters are converted to numbers (A=01, B=02); _6th digit_: indicator, if the plot has been shifted a quarter mu. Example: "p205260": "p" means that this is a plot that is specified. "2" means, that we are at site B. Now the coordinates of the south - west corner: "0526". Since "e" is the fifth letter of the alphabet, this is Plot E26. The last digit "0" means that this plot was not moved by a quarter of a Mu, as some sites in Site A. The 6th digit can also indicate the subplot within the plot. "5", "6", "7", "8" indicate the northwest, northeast, southeast, and southwest quarter plot respectively. Morover, Plots from the main experiment may be labelled in the more ambiguous form of e.g. A32. This indicates a plat either on Site A (29°07'28.2"N 117°54'27.5"E) or Site B (29°05'06.8"N 117°55'44.4"E) of the main experiment. This value only becomes a unique identifier if supported with the "site" information from another cell. Plots labelled in the form of "1_AO1" or "g1_AO1" or "pilot1_AO1" belong to the "Pilot Experiment" (approx location: 29°06'20.2"N 117°55'12.1"E, Jiangxi Province)
3  field name of the sample; Datagroup description: Helper
4  Laboratory number of laboratory of soil science and geoecology in Tübingen
5  depth (lower boundary) of the sample; Datagroup description: Soil depth
6  pH value, mean from two values determined by H20 method. solutionH20 : soil = 2.5:1; Datagroup description: pH value; Instrumentation: electrodes Sentix 81 and WTW pH-meter (derived from datagroup); Instrumentation: electrodes Sentix 81 and WTW pH-meter (derived from datagroup)
7  pH value, mean from two values determined in 1 M KCL; Datagroup description: pH value; Instrumentation: electrodes Sentix 81 and WTW pH-meter (derived from datagroup); Instrumentation: electrodes Sentix 81 and WTW pH-meter (derived from datagroup)
8  total organic nitrogen content; Datagroup description: Nitrogen; Instrumentation: Elemental Analyzer (derived from datagroup); Instrumentation: Elemental Analyzer (derived from datagroup)
9  total soil organic carbon content; Datagroup description: Carbon content
10 total sulphur content; Datagroup description: Sulphur; Instrumentation: heat combustion and thermal conductivity detection using a CNS-Elementar analyser, varioEL III from Elementar (derived from datagroup); Instrumentation: heat combustion and thermal conductivity detection using a CNS-Elementar analyser, varioEL III from Elementar (derived from datagroup); Datagroup description: S content
11 ratio organic carbon/organic nitrogen
   Variable Type Unit
1  category      NA
2  category      NA
3  text          NA
4  number        NA
5  number        cm
6  number        pH
7  number        pH
8  number        Mass-%
9  number        Mass-%
10 number        Mass-%
11 number        ratio
   Instrumentation
1  NA
2  NA
3  NA
4  NA
5  NA
6  electrodes Sentix 81 and WTW pH-meter (derived from datagroup)
7  electrodes Sentix 81 and WTW pH-meter (derived from datagroup)
8  Elemental Analyzer (derived from datagroup)
9  NA
10 heat combustion and thermal conductivity detection using a CNS-Elementar analyser, varioEL III from Elementar (derived from datagroup)
11 NA
   References Keywords
1  NA         location, Site A
2  NA         location, Site A
3  NA         soil base
4  NA         soil base
5  NA         soil, soil depth
6  NA         pH
7  NA         pH
8  NA         SON, nitrogen
9  NA         SOC, carbon
10 NA         S
11 NA         C/N ratio
   Data Group Title
1  Plot name Main experiment (letter, number code)
2  BEF research plot name
3  Helper
4  Laboratory number of Laboratory of Soil Science and Geoecology in Tübingen
5  Soil depth
6  pH value
7  pH value
8  Nitrogen
9  Carbon
10 Sulphur
11 Carbon Nitrogen ratio
   Data Group Description
1  Plot number according to design spreadsheet. Plots are named according to their location on the original spreadsheet used for treatment design. This has letters from West to East and numbers from North to south. Some plots were moved half a gridcell (1 mu) so be suitable for planting (grid cell loctype). Example: B32
2  Reasearch plots of the Biodiversity - Ecosystem functioning experiment (BEF-China). There are three main sites for research plots in the BEF Experiment: Comparative Study Plots (CSP) in the  Gutianshan Nature Reserve (29º8'18" – 29º17'29" N, 118º2'14" – 118º11'12" E, Zhejiang Province Southeast China), having a size of 30x30m^2, measured on the ground. Main Experiment plots have a size of 1 mu, which is about 25x25m^2 in horizontal projection. Pilot Study Plots have a size of 1x1 m^2.  \r\nResearch plots on the main experiment have a "p" in front of their IDs and then a 6 digit code: Plots in the main sites A (29°07'28.2"N 117°54'27.5"E) and B (29°05'06.8"N 117°55'44.4"E) are named according to their position in the original spreadsheet, in which they were designed.  They consist of 6 digits: _1st digit_: Site (1:A, 2:B), _digit 2and3_: southwards row: as in spreadsheets the rows are named from the top to the bottom; _digit 4 and 5_: westward column: as in the original spreadsheet, but the letters are converted to numbers (A=01, B=02); _6th digit_: indicator, if the plot has been shifted a quarter mu.  Example: "p205260": "p" means that this is a plot that is specified.  "2" means, that we are at site B.  Now the coordinates of the south - west corner: "0526".  Since "e" is the fifth letter of the alphabet, this is Plot E26.   The last digit "0" means that this plot was not moved by a quarter of a Mu, as some sites in Site A. The 6th digit can also indicate the subplot within the plot. "5", "6", "7", "8" indicate the northwest, northeast, southeast, and southwest quarter plot respectively.\r\nMorover, Plots from the main experiment may be labelled in the more ambiguous  form of e.g. A32. This indicates a plat either on Site A (29°07'28.2"N 117°54'27.5"E) or Site B (29°05'06.8"N 117°55'44.4"E) of the main experiment. This value only becomes a unique identifier if supported with the "site" information from another cell.\r\nPlots labelled in the form of "1_AO1" or "g1_AO1" or "pilot1_AO1" belong to the "Pilot Experiment" (approx location:  29°06'20.2"N 117°55'12.1"E, Jiangxi Province)
3  Helper column to understand other columns in this data set
4  Laboratory number laboratory Scholten, Kühn, Tübingen.
5  Incremental soil depth as opposed to soil horizon, where each horizon could be of differen depth.
6  In case of H2O: samples were air-dried, sieved < 2mm, solutionH20 : soil = 2.5:1 -- in case of KCL: samples were air-dried, sieved < 2mm, solutionKCL : soil = 2.5:1; pH (KCl) is the maximum potential acidity under the present soil conditions, pH (H2O) is the current acidity; pH (KCl) is the maximum potential acidity under the present soil conditions, pH (H2O) is the current acidity
7  In case of H2O: samples were air-dried, sieved < 2mm, solutionH20 : soil = 2.5:1 -- in case of KCL: samples were air-dried, sieved < 2mm, solutionKCL : soil = 2.5:1; pH (KCl) is the maximum potential acidity under the present soil conditions, pH (H2O) is the current acidity; pH (KCl) is the maximum potential acidity under the present soil conditions, pH (H2O) is the current acidity
8  Nitrogen concentration
9  measurements of Carbon such as concentrations, pools, amount
10 S content: samples were air-dried, sieved < 2mm, ground using a ball mill, using around 40 mg for measurements with vario EL III (Elementar)
11 Carbon Nitrogen ratio

# Cleaning etc.

In [6]:
a_soils |> 
 glimpse()

Rows: 1,643
Columns: 11
$ plot_number <chr> "x13", "x13", "x13", "x13", "x13", "x13", "l9", "l9", "l9"…
$ ptag        <chr> "p124130", "p124130", "p124130", "p124130", "p124130", "p1…
$ sample_num  <chr> "expa-s-x13-1", "expa-s-x13-2", "expa-s-x13-3", "expa-s-x1…
$ lab_num     <chr> "4858", "4859", "4860", "4861", "4862", "4863", "4864", "4…
$ depth_lb    <chr> "5", "10", "20", "30", "40", "50", "5", "10", "20", "30", …
$ p_h_h2o     <chr> "5.06", "5.04", "5.01", "5", "4.98", "5.01", "5.02", "4.83…
$ p_h_k_cl    <chr> "3.9", "3.87", "3.87", "3.91", "3.94", "3.91", "3.79", "3.…
$ n_t         <chr> "0.24330297112464905", "0.21959595382213593", "0.162739068…
$ c_t         <chr> "3.2993035316467285", "2.8164491653442383", "1.80776166915…
$ s_t         <chr> "< 0.05", "< 0.05", "< 0.05", "< 0.05", "< 0.05", "< 0.05"…
$ c_n         <chr> "13.560473661279", "12.82559681234132", "11.10834471635714…

In [7]:
a_soils |> 
distinct(ptag)

    ptag
1   p124130
2   p112090
3   p110070
4   p122160
5   p117230
6   p123130
7   p122111
8   p111230
9   p116240
10  p117210
11  p114280
12  p114210
13  p117070
14  p112120
15  p120140
16  p118150
17  p117150
18  p111040
19  p110210
20  p114290
21  p121150
22  p111210
23  p117240
24  p121140
25  p124140
26  p115190
27  p108081
28  p116250
29  p111030
30  p118090
⋮   ⋮
245 p106350
246 p105320
247 p114060
248 p105300
249 p111080
250 p107250
251 p121110
252 p105240
253 p110290
254 p104320
255 p107190
256 p108270
257 p102361
258 p111090
259 p120100
260 p109300
261 p104310
262 p109270
263 p107160
264 p107310
265 p107330
266 p107340
267 p121100
268 p112200
269 p112190
270 p119100
271 p119090
272 p113190
273 p113180
274 p113200

In [8]:
all_data_joined_lg <- readRDS("datas_and_notebooks/final_datas/all_data_joined_lightlogger.rds")

In [9]:
unique(all_data_joined_lg$subplot)

  [1] "ac32-i"     "ac32-ii"    "ac32-iii"   "ac32-iv"    "ae31-i"
  [6] "ae31-ii"    "ae31-iii"   "ae31-iv"    "ae33-ii"    "ae33-iii"
 [11] "ae33-iv"    "af21-i"     "af21-ii"    "af21-iii"   "af21-iv"
 [16] "af27-i"     "af27-ii"    "af27-iii"   "af27-iv"    "ag24-i"
 [21] "ag24-ii"    "ah31-i"     "ah31-ii"    "ah31-iii"   "ah31-iv"
 [26] "ai12-i"     "ai12-ii"    "ai12-iii"   "ai12-iv"    "ai27-i"
 [31] "ai27-ii"    "ai27-iii"   "ai27-iv"    "ai28-i"     "ai28-ii"
 [36] "ai28-iv"    "aj21-i"     "aj21-ii"    "aj21-iii"   "aj21-iv"
 [41] "ak19-i"     "ak19-iv"    "al10-i"     "al10-ii"    "al10-iii"
 [46] "al10-iv"    "al11-i"     "al11-iii"   "al11-iv"    "al22-i"
 [51] "al22-ii"    "al22-iv"    "al22-i.o"   "al22-ii.o"  "al22-iii.o"
 [56] "al22-iv.o"  "an8-i"      "an8-iv"     "an9-i"      "an9-ii"
 [61] "an9-iii"    "an9-i.o"    "an9-ii.o"   "an9-iii.o"  "an9-iv.o"
 [66] "an11-i"     "an11-ii"    "an11-iii"   "an11-iv"    "an13-i"
 [71] "an13-ii"    "an13-iii"   "an13-iv"    "ao22-i"     "ao22-iii"
 [76] "ao27-ii"    "ao27-iii"   "ao27-iv"    "ap19-i"     "ap19-ii"
 [81] "ap19-iii"   "ap19-iv"    "ap23-i"     "ap26-i"     "ap26-ii"
 [86] "ap26-iii"   "ap26-iv"    "aq21-i"     "aq21-ii"    "aq21-iii"
 [91] "aq21-iv"    "aq9-i"      "aq9-iv"     "aq9-i.o"    "ar14-ii"
 [96] "ar14-iv"    "as10-i"     "as10-ii"    "as10-iii"   "as10-iv"
[101] "as10-i.o"   "as10-ii.o"  "as10-iii.o" "as10-iv.o"  "at15-i"
[106] "at15-iii"   "at15-iv"    "at15-i.o"   "at15-ii.o"  "at15-iii.o"
[111] "at15-iv.o"  "awx12-i"    "awx12-ii"   "awx12-iii"  "awx12-iv"
[116] "aw14-i"     "aw14-ii"    "aw14-iii"   "aw14-iv"    "bg28-i"
[121] "bg28-ii"    "bg28-iii"   "bg28-iv"    "bi25-i"     "bi25-ii"
[126] "bi25-iii"   "bi25-iv"    "bj29-i"     "bj29-ii"    "bj29-iii"
[131] "bj29-iv"    "bj29-i.o"   "bj29-ii.o"  "bj29-iii.o" "bj29-iv.o"
[136] "bm22-i"     "bm22-ii"    "bm22-iii"   "bm22-iv"    "bm24-i"
[141] "bm24-ii"    "bm24-iii"   "bm24-iv"    "bm29-i"     "bm29-ii"
[146] "bm29-iii"   "bm29-iv"    "bm7-i"      "bm7-ii"     "bm7-iii"
[151] "bm7-iv"     "bn28-i"     "bn28-ii"    "bn28-iii"   "bn28-iv"
[156] "bn5-i"      "bn5-ii"     "bn5-iii"    "bn5-iv"     "bo27-i"
[161] "bo27-ii"    "bo27-iii"   "bo27-iv"    "bo31-i"     "bo31-ii"
[166] "bo31-iii"   "bo31-iv"    "bq17-i"     "bq17-ii"    "bq17-iii"
[171] "bq17-iv"    "bq17-i.o"   "bq17-ii.o"  "bq17-iv.o"  "bq27-i"
[176] "bq27-ii"    "bq27-iii"   "bq29-i"     "bq29-ii"    "bq29-iii"
[181] "bq29-iv"    "br29-i"     "br29-ii"    "br29-iv"    "br3-i"
[186] "br3-ii"     "br3-iv"     "bs18-ii"    "bs18-iii"   "bs18-ii.o"
[191] "bs18-iii.o" "bs22-i"     "bs22-ii"    "bs22-iii"   "bs22-iv"
[196] "bs22-i.o"   "bs22-ii.o"  "bs22-iii.o" "bs22-iv.o"  "bt13-i"
[201] "bt13-ii"    "bt13-iii"   "bt13-iv"    "bt29-i"     "bt29-iii"
[206] "bt29-iv"    "bt8-i"      "bt8-ii"     "bt8-iii"    "bt8-iv"
[211] "bt8-i.o"    "bt8-ii.o"   "bt8-iii.o"  "bt8-iv.o"   "bu16-i"
[216] "bu16-iii"   "bu16-iv"    "bu27-i"     "bu27-ii"    "bu27-iii"
[221] "bu27-iv"    "bv15-i"     "bv15-ii"    "bv15-iii"   "bv15-iv"
[226] "bv19-i"     "bv19-ii"    "bv19-iii"   "bv19-iv"    "bv23-i"
[231] "bv23-ii"    "bv23-iii"   "bv23-iv"    "bv24-i"     "bv24-ii"
[236] "bv24-iii"   "bv24-iv"    "bw10-i"     "bw10-ii"    "bw10-iii"
[241] "bw10-iv"    "bw11-i"     "bw11-ii"    "bw11-iii"   "bw11-iv"
[246] "bx21-i"     "bx21-ii"    "bx21-iii"   "bx21-iv"    "ae33.ii"
[251] "ao22-ii"    "aw14"       "bq27-iv"    "bt29-iiiv"  "bx21-ii.0"
[256] "ag24-iii"   "bo29-iv"    "bx21-ii.o"

In [10]:
library(dplyr)
library(stringr)

# Hilfsfunktion bleibt gleich
num_to_letters <- function(n) {
  # n should be numeric or coercible to numeric
  all_letters <- c(letters, paste0("a", letters))
  n_num <- as.numeric(n)
  # Return NA for invalid indices
  n_num[is.na(n_num) | n_num < 1 | n_num > length(all_letters)] <- NA
  return(all_letters[n_num])
}

# Für a_soils
a_soils_clean <- a_soils %>%
  mutate(
    ptag_clean = tolower(ptag),
    site_code = str_sub(ptag_clean, 2, 2),
    letter_num = str_sub(ptag_clean, 3, 4),
    plot_num = str_sub(ptag_clean, 5, 6),
    subplot_digit = str_sub(ptag_clean, 7, 7)
  ) %>%
  mutate(
    plot_letter = num_to_letters(letter_num),
    subplot_roman = case_when(
      subplot_digit == "0" ~ NA_character_,
      subplot_digit == "5" ~ "i",
      subplot_digit == "6" ~ "ii",
      subplot_digit == "7" ~ "iii",
      subplot_digit == "8" ~ "iv",
      TRUE ~ NA_character_
    ),
    join_id = if_else(
      is.na(subplot_roman),
      paste0(plot_letter, as.numeric(plot_num)),
      paste0(plot_letter, as.numeric(plot_num), "-", subplot_roman)
    )
  ) %>%
  select(ptag, sample_num, join_id) %>%
  distinct() %>%
  full_join(a_soils, by = c("ptag", "sample_num")) |> 
  mutate(join_id = paste0("a", join_id))  # <-- Korrigiert: paste0 statt paste

# Ausgabe der join_id-Spalten zur Kontrolle
a_soils_clean %>% select(ptag, join_id)

     ptag    join_id
1    p124130 ax13
2    p124130 ax13
3    p124130 ax13
4    p124130 ax13
5    p124130 ax13
6    p124130 ax13
7    p112090 al9
8    p112090 al9
9    p112090 al9
10   p112090 al9
11   p112090 al9
12   p112090 al9
13   p110070 aj7
14   p110070 aj7
15   p110070 aj7
16   p110070 aj7
17   p110070 aj7
18   p110070 aj7
19   p122160 av16
20   p122160 av16
21   p122160 av16
22   p122160 av16
23   p122160 av16
24   p122160 av16
25   p117230 aq23
26   p117230 aq23
27   p117230 aq23
28   p117230 aq23
29   p117230 aq23
30   p117230 aq23
⋮    ⋮       ⋮
1614 p112190 al19
1615 p112190 al19
1616 p112190 al19
1617 p112190 al19
1618 p112190 al19
1619 p119100 as10
1620 p119100 as10
1621 p119100 as10
1622 p119100 as10
1623 p119100 as10
1624 p119090 as9
1625 p119090 as9
1626 p119090 as9
1627 p119090 as9
1628 p119090 as9
1629 p113190 am19
1630 p113190 am19
1631 p113190 am19
1632 p113190 am19
1633 p113190 am19
1634 p113180 am18
1635 p113180 am18
1636 p113180 am18
1637 p113180 am18
1638 p113180 am18
1639 p113200 am20
1640 p113200 am20
1641 p113200 am20
1642 p113200 am20
1643 p113200 am20

In [11]:
b_soils |> 
 glimpse()

Rows: 1,636
Columns: 10
$ plot_number <chr> "r20", "r20", "r20", "r20", "r20", "r20", "q24", "q24", "q…
$ sample_num  <chr> "expb-s-r20-1", "expb-s-r20-2", "expb-s-r20-3", "expb-s-r2…
$ lab_num     <chr> "6842", "6843", "6844", "6845", "6846", "6847", "6848", "6…
$ depth_lb    <chr> "5", "10", "20", "30", "40", "50", "5", "10", "20", "30", …
$ p_h_h2o     <chr> "4.28", "4.29", "4.34", "4.64", "4.66", "4.6", "4.58", "4.…
$ p_h_k_cl    <chr> "3.49", "3.38", "3.35", "3.66", "3.7", "3.69", "3.56", "3.…
$ n_t         <chr> "0.1049867570400238", "0.07884521037340164", "0.0655405595…
$ c_t         <chr> "1.2762118577957153", "0.744991660118103", "0.442470729351…
$ s_t         <chr> "< 0.05", "< 0.05", "< 0.05", "< 0.05", "< 0.05", "< 0.05"…
$ c_n         <chr> "12.155931793465996", "9.44878777784865", "6.7510978258336…

In [12]:
# Für a_soils
b_soils_clean <- b_soils |>
  mutate(join_id = paste0("b", plot_number)) |> 
  distinct() 
glimpse(b_soils_clean)

Rows: 1,636
Columns: 11
$ plot_number <chr> "r20", "r20", "r20", "r20", "r20", "r20", "q24", "q24", "q…
$ sample_num  <chr> "expb-s-r20-1", "expb-s-r20-2", "expb-s-r20-3", "expb-s-r2…
$ lab_num     <chr> "6842", "6843", "6844", "6845", "6846", "6847", "6848", "6…
$ depth_lb    <chr> "5", "10", "20", "30", "40", "50", "5", "10", "20", "30", …
$ p_h_h2o     <chr> "4.28", "4.29", "4.34", "4.64", "4.66", "4.6", "4.58", "4.…
$ p_h_k_cl    <chr> "3.49", "3.38", "3.35", "3.66", "3.7", "3.69", "3.56", "3.…
$ n_t         <chr> "0.1049867570400238", "0.07884521037340164", "0.0655405595…
$ c_t         <chr> "1.2762118577957153", "0.744991660118103", "0.442470729351…
$ s_t         <chr> "< 0.05", "< 0.05", "< 0.05", "< 0.05", "< 0.05", "< 0.05"…
$ c_n         <chr> "12.155931793465996", "9.44878777784865", "6.7510978258336…
$ join_id     <chr> "br20", "br20", "br20", "br20", "br20", "br20", "bq24", "b…

In [13]:
soils_joined <- a_soils_clean |> 
 full_join(b_soils_clean) |> 
 select(-c(sample_num, ptag, plot_number, lab_num))

Joining with `by = join_by(sample_num, join_id, plot_number, lab_num, depth_lb,
p_h_h2o, p_h_k_cl, n_t, c_t, s_t, c_n)`

In [14]:
soils_joined |> 
  count(s_t)

   s_t                  n
1  0.05011679604649544     1
2  0.050158750265836716    1
3  0.05051339045166969     1
4  0.05101203918457031     1
5  0.05122085288167        1
6  0.051402416080236435    1
7  0.051483020186424255    1
8  0.05155885964632034     1
9  0.052035801112651825    1
10 0.05243658274412155     1
11 0.053225964307785034    1
12 0.053360600024461746    1
13 0.0534929558634758      1
14 0.05434996262192726     1
15 0.054978176951408386    1
16 0.05594220757484436     1
17 0.05677824467420578     1
18 0.05696190893650055     1
19 0.05723116546869278     1
20 0.05734296888113022     1
21 0.05799064785242081     1
22 0.058319687843322754    1
23 0.059096354991197586    1
24 < 0.05               3256

In [15]:
soils_joined2 <- soils_joined |> 
  mutate(
    depth_lb = as.numeric(depth_lb),
    p_h_h2o = as.numeric(p_h_h2o),
    p_h_k_cl = as.numeric(p_h_k_cl),
    n_t = as.numeric(n_t),
    c_t = as.numeric(c_t), 
	c_n = as.numeric(c_n)
  ) |> 
 rename("plot" = join_id) |> 
 group_by(plot) |> 
 summarise_if(is.numeric, mean)

Warning message:
“There were 2 warnings in `mutate()`.
The first warning was:
ℹ In argument: `p_h_h2o = as.numeric(p_h_h2o)`.
Caused by warning:
! NAs introduced by coercion
ℹ Run `dplyr::last_dplyr_warnings()` to see the 1 remaining warning.”

s_t wird entfernt wegen zu geringen Werten (hauptsächlich < 0.05). Alle Werte werden über die Tiefe hinweg gemittelt.

In [16]:
glimpse(soils_joined2)

Rows: 565
Columns: 7
$ plot     <chr> "ab34", "ab35", "ab36", "ab38", "ac31", "ac32", "ac33", "ac37…
$ depth_lb <dbl> 25.83333, 25.83333, 25.83333, 25.83333, 25.83333, 25.83333, 2…
$ p_h_h2o  <dbl> 4.605000, 4.558333, 4.616667, 4.606667, 4.635000, 4.695000, 4…
$ p_h_k_cl <dbl> 3.745000, 3.630000, 3.731667, 3.720000, 3.748333, 3.743333, 3…
$ n_t      <dbl> 0.15494267, 0.14802511, 0.14737287, 0.14715984, 0.14811081, 0…
$ c_t      <dbl> 2.3090774, 2.0686276, 1.9780217, 2.1376717, 2.0648535, 2.0001…
$ c_n      <dbl> 14.142631, 12.660410, 12.844497, 13.172830, 12.368729, 12.481…

In [17]:
a_soils_clean |> 
select(ptag, sample_num, join_id, lab_num, depth_lb)

     ptag    sample_num   join_id lab_num depth_lb
1    p124130 expa-s-x13-1 ax13    4858    5
2    p124130 expa-s-x13-2 ax13    4859    10
3    p124130 expa-s-x13-3 ax13    4860    20
4    p124130 expa-s-x13-4 ax13    4861    30
5    p124130 expa-s-x13-5 ax13    4862    40
6    p124130 expa-s-x13-6 ax13    4863    50
7    p112090 expa-s-l9-1  al9     4864    5
8    p112090 expa-s-l9-2  al9     4865    10
9    p112090 expa-s-l9-3  al9     4866    20
10   p112090 expa-s-l9-4  al9     4867    30
11   p112090 expa-s-l9-5  al9     4868    40
12   p112090 expa-s-l9-6  al9     4869    50
13   p110070 expa-s-j7-1  aj7     4870    5
14   p110070 expa-s-j7-2  aj7     4871    10
15   p110070 expa-s-j7-3  aj7     4872    20
16   p110070 expa-s-j7-4  aj7     4873    30
17   p110070 expa-s-j7-5  aj7     4874    40
18   p110070 expa-s-j7-6  aj7     4875    50
19   p122160 expa-s-v16-1 av16    4876    5
20   p122160 expa-s-v16-2 av16    4877    10
21   p122160 expa-s-v16-3 av16    4878    20
22   p122160 expa-s-v16-4 av16    4879    30
23   p122160 expa-s-v16-5 av16    4880    40
24   p122160 expa-s-v16-6 av16    4881    50
25   p117230 expa-s-q23-1 aq23    4882    5
26   p117230 expa-s-q23-2 aq23    4883    10
27   p117230 expa-s-q23-3 aq23    4884    20
28   p117230 expa-s-q23-4 aq23    4885    30
29   p117230 expa-s-q23-5 aq23    4886    40
30   p117230 expa-s-q23-6 aq23    4887    50
⋮    ⋮       ⋮            ⋮       ⋮       ⋮
1614 p112190 expa-s-l19-1 al19    9142    5
1615 p112190 expa-s-l19-2 al19    9143    10
1616 p112190 expa-s-l19-3 al19    9144    20
1617 p112190 expa-s-l19-4 al19    9145    30
1618 p112190 expa-s-l19-5 al19    9146    40
1619 p119100 expa-s-s10-1 as10    9147    5
1620 p119100 expa-s-s10-2 as10    9148    10
1621 p119100 expa-s-s10-3 as10    9149    20
1622 p119100 expa-s-s10-4 as10    9150    30
1623 p119100 expa-s-s10-5 as10    9151    40
1624 p119090 expa-s-s9-1  as9     9152    5
1625 p119090 expa-s-s9-2  as9     9153    10
1626 p119090 expa-s-s9-3  as9     9154    20
1627 p119090 expa-s-s9-4  as9     9155    30
1628 p119090 expa-s-s9-5  as9     9156    40
1629 p113190 expa-s-m19-1 am19    9157    5
1630 p113190 expa-s-m19-2 am19    9158    10
1631 p113190 expa-s-m19-3 am19    9159    20
1632 p113190 expa-s-m19-4 am19    9160    30
1633 p113190 expa-s-m19-5 am19    9161    40
1634 p113180 expa-s-m18-1 am18    9162    5
1635 p113180 expa-s-m18-2 am18    9163    10
1636 p113180 expa-s-m18-3 am18    9164    20
1637 p113180 expa-s-m18-4 am18    9165    30
1638 p113180 expa-s-m18-5 am18    9166    40
1639 p113200 expa-s-m20-1 am20    9167    5
1640 p113200 expa-s-m20-2 am20    9168    10
1641 p113200 expa-s-m20-3 am20    9169    20
1642 p113200 expa-s-m20-4 am20    9170    30
1643 p113200 expa-s-m20-5 am20    9171    40

In [18]:
soils_joined3 <- soils_joined2 |>
  group_by(plot) |>
  arrange(depth_lb) |>
  mutate(
    prev_depth = lag(depth_lb, default = 0),
    layer_thickness = depth_lb - prev_depth
  ) |>
  summarise(
    soil_h20 = sum(p_h_h2o * layer_thickness) / sum(layer_thickness),
    soil_ph_k_cl = sum(p_h_k_cl * layer_thickness) / sum(layer_thickness),
    soil_n = sum(n_t * layer_thickness) / sum(layer_thickness),
    soil_c = sum(c_t * layer_thickness) / sum(layer_thickness),
    soil_c_n = sum(c_n * layer_thickness) / sum(layer_thickness),
    .groups = "drop"
  )

In [19]:
all_data_joined_lg_soil <- all_data_joined_lg |> 
 left_join(soils_joined3) 

all_data_joined_lg_soil |> 
 saveRDS(file = "datas_and_notebooks/final_datas/all_data_joined.rds")

Joining with `by = join_by(plot)`